version: '2'
services:
  static:
    image: mattrayner/lamp:latest-1604-php7 # todo: enginx
    restart: always
    depends_on: api
    volumes:
      - "./static:/app"
    ports:
      - "80:80"
  api:
    image: mattrayner/lamp:latest-1604-php7 # todo phpfpm
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - "./api:/app"
    ports:
      - "9001:80"
    environment:
      - ES_HOST=http://geocode1.essch.ru:9200
#    healthcheck:
#      test: ["CMD" "curl" "-f" "http://geocode1.essch.ru:9200"]
#      interval: 2s
#      timeout: 5s
  web:
    image: httpd:2.4
    ports:
      - "9090:80"
    volumes:
      - .:/usr/local/apache2/htdocs/ #? CMD ["apache2", "-DFOREGROUND"]
#      - ./apache2_conf:/usr/local/apache2/conf/httpd.conf
  kibana:
    image: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
