version: '2'
services:
  elasticsearch:
    image: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - "./data_es:/usr/share/elasticsearch/data:rw"
      - "./config_es:/usr/share/elasticsearch/config"
    environment:
      - ES_JAVA_OPTS="-Xms512m -Xmx512m"
  app:
    image: fauria/lamp
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ".:/var/www/html"
    ports:
      - "80:80"
    entrypoint:
      - ES_HOST="http://geocode1.essch.ru:9200/"
  kibana:
    image: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    # environment:
    # ELASTICSEARCH_URL=http://some-elasticsearch:9200
